### ISSUE TITLE
Example is not working with AIIDA 1.5.0

### ISSUE THREAD

**Issue by dgwvfxn** [aiidateam/aiida-nwchem#13]
Hi,

I want to use aiida to control my NWCHEM workflows. However, I noticed that the example provided in this repo is out-dated. When I tried to use aiida-nwchem/tests/examples/test_nwchem.py, I got several issues:
1) aiida.common.example_helper no longer exist.
2) code.new_calc() doesn't work because new_calc function no longer exist. 

Could you help update the docs and examples? It would be really helpful that if I can have a working example of setting the structures and parameters of a nwchem job.

**Comment by ConradJohnston** [comment]
Hello!

Many thanks for your interest in the plugin and AiiDA. 
AiiDA 1.x+ is now supported in the develop branch.

Support was added in 5a925b227c2ecbd7a2220e734af43bc953990142.
