### ISSUE TITLE
Support for aiida v2?

### ISSUE THREAD

**Issue by francescalb** [aiidateam/aiida-nwchem#26]
I would like to try out nwchem with aiida, but see that it is not supoprting aiida v2. As I am new to AiiDA I would like to start from the latest version. Does aiida-nwchem support aiidav2? If not, does changing it to support v2 require a lot of effort?

**Comment by ltalirz** [comment]
I've been using the plugin with aiida 2 (no extensive testing but what I needed worked)

**Comment by francescalb** [comment]
Thank you, I will try it out with aiidav2 then.

**Comment by sphuber** [comment]
Just to let you know that although certain things might work, the package is quite outdated. Definitely give it a try already and report back if you come across any issues. I am now working on fully updating the package adding tests etc and making an official 2.0 compatible release.

**Comment by francescalb** [comment]
> 

That is great to know! My question actually orginated from trying to run the tests and see if I coul dlearn how to use it from them.

**Comment by ltalirz** [comment]
I introduced a bug in the last commit (shame on me).

Anyhow https://github.com/aiidateam/aiida-nwchem/pull/27 is ready to merge, and you can have a look at the `tests/test_calculations.py` file to see how to use the plugin

**Comment by daniel-sintef** [comment]
Thanks a lot for reaching out @sphuber & @ltalirz!

**Comment by sphuber** [comment]
I have just updated the package to modern standards. It now also has continuous-integration running unit tests. I have made a new release `v2.1.1` with all these changes: https://pypi.org/project/aiida-nwchem/  This still supports AiiDA v1.x but I will now update the package to be fully v2.0 compliant and add support for more recent Python versions. Please try out `aiida-nwchem==2.1.1` and open an issue if you experiencing any problems. Thanks

**Comment by sphuber** [comment]
Ok, hot off the press: [`aiida-nwchem==3.0`](https://pypi.org/project/aiida-nwchem/3.0.0/). It is fully compatible with AiiDA v2.0 and addresses deprecation warnings and such. Should be all good to go now! :+1:

**Comment by francescalb** [comment]
Fantastic. I'll try out and see if I manage to aiidafy my nwchem-work :)
